---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: docs-letsencrypt
  namespace: techmonkey-docs
spec:
  acme:
    email: docs@techmonkey.cc
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: docs-secret-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: traefik
